# Generated by Django 4.0.6 on 2024-07-14 01:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingredients', models.JSONField()),
                ('instructions', models.JSONField()),
                ('image_url', models.URLField(blank=True)),
                ('time_to_cook', models.IntegerField(help_text='Time to cook in minutes')),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
