# Generated by Django 4.0.6 on 2024-07-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='user_full_name',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
