# Generated by Django 4.0.6 on 2024-07-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='uid',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
